server:    
  port: 8761 # 1번

spring: 
  application:
    name: discovery-service # 2번

eureka:
  instance:
    ipAddress: 127.0.0.1
  client:
    register-with-eureka: false # 3번
    fetch-registry: false  # 4번