app:
  ver: v1.0

server:
  port: 8092
  
spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:mariadb://jhk-db.cjvrebigithi.ap-northeast-2.rds.amazonaws.com/stock?autoReconnect=true
    #url: jdbc:mariadb://127.0.0.1/stock?autoReconnect=true
    username: jhk
    password: '{cipher}27eeb3db89cf4d8d6daa8c1bc54596fa5e912e494668f2ad2e7c5b351a97a264'
    driver-class-name: org.mariadb.jdbc.Driver

springfox:
  documentation:
    swagger:
      v2:
        path: /${app.ver}/api-docs

eureka:
  instance:
    instance-id: stock-microservice-instance
    hostname: 127.0.0.1
    
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  
kafka:
  topic: 
    cheg: stock.cheg
    program: stock.program
    business: stock.business
    stocks: stock.stocks
  bootstrap: 1.240.167.231:9092
  group: stock.group
    
#logging:
  #file:
    #name: ${user.dir}/log/test.log  # 로깅 파일 위치이다.
    #max-history: 7 # 로그 파일 삭제 주기이다. 7일 이후 로그는 삭제한다.
    #max-size: 10MB  # 로그 파일 하나당 최대 파일 사이즈이다.
  #level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
    #com.project.study : error
    #com.project.study.controller : debug